package gui;

import javax.swing.*;
import java.awt.*;

public class Registration extends JFrame {
    JPanel MainFrame;
    JPanel CenterMainFrame;
    JPanel BottomMainFrame;
    JButton nextButton;
    JTextField UserNameTextField;
    JTextField PasswordTextField;
    JLabel UserNameLabel;
    JLabel PasswordLabel;
    JLabel QuestionLabel;
    JCheckBox QuestionCheckbox;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public Registration() {
        $$$setupUI$$$();
        setTitle("Registration");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(300, 300);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MainFrame = new JPanel();
        MainFrame.setLayout(new BorderLayout(0, 0));
        MainFrame.setEnabled(true);
        CenterMainFrame = new JPanel();
        CenterMainFrame.setLayout(new com.jgoodies.forms.layout.FormLayout("fill:234px:noGrow,left:12dlu:noGrow,fill:1586px:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        MainFrame.add(CenterMainFrame, BorderLayout.CENTER);
        UserNameLabel = new JLabel();
        UserNameLabel.setText("Please enter a username");
        com.jgoodies.forms.layout.CellConstraints cc = new com.jgoodies.forms.layout.CellConstraints();
        CenterMainFrame.add(UserNameLabel, cc.xy(1, 1));
        UserNameTextField = new JTextField();
        UserNameTextField.setText("");
        CenterMainFrame.add(UserNameTextField, cc.xyw(1, 3, 3, com.jgoodies.forms.layout.CellConstraints.FILL, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        PasswordLabel = new JLabel();
        PasswordLabel.setText("Please enter a password");
        CenterMainFrame.add(PasswordLabel, cc.xy(1, 5));
        PasswordTextField = new JTextField();
        PasswordTextField.setText("");
        CenterMainFrame.add(PasswordTextField, cc.xyw(1, 7, 3, com.jgoodies.forms.layout.CellConstraints.FILL, com.jgoodies.forms.layout.CellConstraints.DEFAULT));
        QuestionCheckbox = new JCheckBox();
        QuestionCheckbox.setText("");
        CenterMainFrame.add(QuestionCheckbox, cc.xy(3, 9));
        QuestionLabel = new JLabel();
        QuestionLabel.setText("Are you a job owner?");
        CenterMainFrame.add(QuestionLabel, cc.xy(1, 9));
        BottomMainFrame = new JPanel();
        BottomMainFrame.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        MainFrame.add(BottomMainFrame, BorderLayout.SOUTH);
        nextButton.setBackground(new Color(-11557803));
        nextButton.setEnabled(true);
        nextButton.setHorizontalAlignment(0);
        nextButton.setHorizontalTextPosition(0);
        nextButton.setText("Next");
        BottomMainFrame.add(nextButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainFrame;
    }
}
